# Generated by Django 5.0.7 on 2024-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_baby_clothes_images')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('affiliate_link', models.CharField(max_length=2083)),
                ('date_and_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'All Baby Clothes',
                'ordering': ('-date_and_time_created',),
            },
        ),
    ]
