# Generated by Django 5.0.7 on 2024-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_message_options_remove_message_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogandreview',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
