# Generated by Django 5.0.7 on 2024-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_blogandreview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogandreview',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogandreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_and_review_images'),
        ),
        migrations.AlterField(
            model_name='homepagesoftware',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_software_images'),
        ),
    ]
