# Generated by Django 5.0.7 on 2024-12-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_blogandreview_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogandreview',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
